### ISSUE TITLE
Rom audio issues

### ISSUE THREAD

**Issue by Jasonh1981** [vpinball/pinmame#147]
Upgraded from v3.6-369-102e419 (Mar 13) to v3.6-573-5d6459d for altsound support. Voice audio for Jokerz (jokrz_l6) is extremely loud and clipping. Voice audio for Bride of Pinbot (bop_l7) is very low and barely audible. Reverting back to the version from March 13 fixed the issue.

**Comment by droscoe** [comment]
> Upgraded from v3.6-369-102e419 (Mar 13) to v3.6-573-5d6459d for altsound 2.0 support. Voice audio for Jokerz (jokrz_l6) is extremely loud and clipping. Voice audio for Bride of Pinbot (bop_l7) is very low and barely audible. Reverting back to the version from March 13 fixed the issue.

Are either of these using an AltSound package?

**Comment by Jasonh1981** [comment]
> > Upgraded from v3.6-369-102e419 (Mar 13) to v3.6-573-5d6459d for altsound 2.0 support. Voice audio for Jokerz (jokrz_l6) is extremely loud and clipping. Voice audio for Bride of Pinbot (bop_l7) is very low and barely audible. Reverting back to the version from March 13 fixed the issue.
> 
> Are either of these using an AltSound package?

No, both are stock roms.

**Comment by toxieainc** [comment]
Whoops, sounds like some of my cleanups/fixes then.

**Comment by toxieainc** [comment]
Actually, its the update to the new HC55516 core that caused this, i just compared https://github.com/vpinball/pinmame/actions/runs/5170901186 with https://github.com/vpinball/pinmame/actions/runs/5168244031 .
Jokerz sounds fine with the old implementation, but introduced some kind of noise/clipping with the new one.

@mjrgh to the rescue, please!

**Comment by mjrgh** [comment]
Yeah, I was a little afraid that the different loudness curve would throw things off for some game.  The audio stream mixing levels will probably have to be adjusted for some sounds boards and/or individual games.  You might want to just set the HC55516 decoding logic back to the old PinMame implementation until someone with enough patience can run through all of the games and tweak the levels as needed.  The old or new implementation logic is run-time selectable - globally through hc55516_use_chip_logic in hc55516.cpp, so setting that default value to 0 would restore the old logic by default.  It could be even be selected on a game-by-game or board-by-board basis (so that the audio level testing and tweaking mentioned above doesn't need to be a gargantuan all-or-nothing task) with an extension to the MachineSound struct, but I didn't want to mess with that.

**Comment by toxieainc** [comment]
@mjrgh I fear that at least with Jokerz its something else. Tuning down the volume for it (even very aggressively) still keeps the 'noise'. Could you please look into this special case?

**Comment by mjrgh** [comment]
Okay, I'll take a look when I have a chance.  I assume this is a confirmed regression - it was working properly with the old hc55516 implementation?  Does it work properly with the new code if you set hc55516_use_chip_logic to zero?

**Comment by toxieainc** [comment]
Didn't try hc55516_use_chip_logic=0 yet, just comparing builds before your commit and after (see above).

**Comment by mjrgh** [comment]
Great, let me know if you have a chance - I’ll look into it when I can but it’s something easy to try in the meantime if you’re playing around with it anyway.  Another thing to try is just rolling back hc55516.cpp in its entirety and see if that fixes it.  It’s perfectly plausible the regression was caused by the hc logic change, but I don’t have a theory of how it would only affect this one game, so I’m thinking it’s more likely to be something that changed elsewhere, like maybe wpcsnd.c, since Jokerz has always been a special case there.

**Comment by toxieainc** [comment]
hc55516_use_chip_logic = 0 works same as before i'd say.

**Comment by toxieainc** [comment]
It's definetly due to the clipping that happens (-512..511), but why it happens/its even necessary? No clue.. Other games seem to rarely encounter this, if at all.

**Comment by mjrgh** [comment]
Excellent data - thanks for the update.  The 10-bit saturation step is based on the MAME decap logic, so it's accurate emulation of the original equipment (presuming that the decap was accurate and MAME's translation of the decap to C was accurate).  However, I think I see what's different about Joikerz - looking at the Jokerz sound board, it looks like they used the HC55564 variant of the chip.  The decap only covered xxx16, as far as I can tell, but the MAME code has what I take to be guesses about the logic parameters for xxx32, which I think is the same internally as xxx64 other than maximum clock speed.  Based on the Jokerz behavior, my guess is that xxx32/64 had a larger internal accumulator than xxx16, perhaps another bit or two wider, which the MAME code didn't account for.  I'll have to experiment with that. 

I think the MachineSound will have to be extended somehow to let the sound board specify which HC variant to use.

**Comment by toxieainc** [comment]
Actually, its even more confusing than that, after some research (more like a bottomless pit ;)).
Seems like Williams/Bally used pretty much every variant over the course of time, so i found 55516 for the early games, 55532, 55536 and 55564 (not to mention the mixed use of 55516 or MC3417 on earlier game schematics).
For Jokerz, its especially weird (might be similar to other Sys11's though): The schematics show a 55516 on the CPU board (U3), the part list mentions a 55536, and the service bulletin a 55564! (so i think it might actually be really have been the 55564?!)

Some pinside thread mentions that its possible to use newer chips on most older boards, so this part may currently be fine, unless we want to be pedantic.

**Comment by mjrgh** [comment]
Yes, the actual parts used seem to vary.  They're definitely not all interchangeable electrically, but what's not clear from the data sheets is how they differ internally in the processing logic.  The data sheets have nothing to say about the processing logic beyond specifying the parameters of the analog filter system they purport to implement, and as far as that goes they all agree (except for an inconsistency on the 16/32 data sheet between the functional block diagram and the table of electrical characteristics, where the syllabic filter time constant is specified as either 0.4ms or 4ms, depending on which part you're looking at; our old code uses the 4ms value, and that yields values consistent with the decap, so I'd bet on that as the one in the data sheet that's not wrong).  So a C++ emulation shouldn't have to care which chip is which - you might not be able to plug a physical 64 into a socket built for a 36, but take away the wiring and they all seem to implement the same math.

**Comment by mjrgh** [comment]
Okay, found it, fixed it.  The fix is so simple that I just pushed it directly.  It's the stupidest thing ever. All of our elaborate conspiracy theories were ridiculous red herrings.  It's got nothing to do with clipping or chip differences.  It's just a dumb memory corruption when there are two sound boards, due to the way I "cleverly" set up the new/old dynamic code handling as a union so that it wouldn't waste memory with state variables for the implementation that's not in use at any given time.  Turns out that there were some cases where PinMame wanted to write to the "old" side of the struct even when the new side was selected - specifically in hc55516_set_gain().  That scribbled over the syllabic filter register and sent the whole state off into crazy land.  It's amazing that anything resembling sound was coming out of it, but I guess that's CVSD's legendary noisy-channel tolerance for you.  I guess I only tested initially against WPC89 games, which have only one sound board and so purely by accident don't run through the code path that screwed things up.

**Comment by toxieainc** [comment]
Nice!

I will still have an eye on the changes that LordNightmare will commit, maybe some older games rely on some of the quirks of the 55516/32 chips..

**Comment by toxieainc** [comment]
Oh, and i will also tweak at least the WPCS/DMD machines some more, they are definetly a bit too silent now..

**Comment by mjrgh** [comment]
> I will still have an eye on the changes that LordNightmare will commit, maybe some older games rely on some of the quirks of the 55516/32 chips..

I think he was just talking about DC offset removal for the DAC, so unrelated to HC (except to the extent that the streams are combined additively into the final mix, thus the impact of an excessively large DC offset from another chip), but maybe I misunderstood.

> Oh, and i will also tweak at least the WPCS/DMD machines some more, they are definetly a bit too silent now..

Great, I'm sure there are some cases - the new algorithm definitely results in a slight change to the loudness output of the chip.

**Comment by toxieainc** [comment]
He also mentioned 2 bugs that are in the HC55516/32 chips that he will correct for the 36/64 variants. I don't know if these exist in your port though.

**Comment by mjrgh** [comment]
> He also mentioned 2 bugs that are in the HC55516/32 chips that he will correct for the 36/64 variants. I don't know if these exist in your port though.

Those are interesting details about the /FZ behavior in his remarks - I hadn't seen those until you mentioned them.  But you're right, it doesn't look like it'll affect VPM, since VPM's version of the chip emulator doesn't even implement the /FZ line.  It must have never been needed, presumably because it's not wired to a controlled input on any of the pinball sound boards.  I spot-checked a couple of System 11 schematics just now, and /FZ is indeed just pulled high on the ones I checked.

**Comment by toxieainc** [comment]
Not yet. Only the part with the broken HC555XX.
I'm still fiddling with the necessary volume rebalancing (BOP and many many more).
