### ISSUE TITLE
Some tables DOF broken (since v1108) : no contactors/solenoids only for flippers.

### ISSUE THREAD

**Issue by Dicentim974** [vpinball/pinmame#359]
Hi, I've noticed that Flipper's contactors don't work anymore for Gilligan's island.
I tried with several recent versions including the latest VPinMAME-sc-3.6.0-1122-79a301d-win-x64. 
It works ok with VPinMAME-sc-3.6.0-998-a77c2d2-win-x64.
Thanks for your help.
![image png 83560f582cdb63bbacc60ceae1571810](https://github.com/user-attachments/assets/4d7011a9-a0fd-46f7-ab2f-71762627f0f3)

**Comment by Dicentim974** [comment]
Hi please note someone reported than VPinMAME-sc-3.6.0-1038-4b9b961 is also good

**Comment by Dicentim974** [comment]
Hi, I've also noticed another issue with flashers on the latest version on VpinMame. Flasher are way to flashy on certain tables like 24, Scared Stiff... It's ok with 1122 version but not with latest betas. Thanks again for your great work !

**Comment by Dicentim974** [comment]
> This looks like an incomplete VPX update. Did you make a VPX (not VPM) update ? and if so, did you updated everything, including scripts and shaders ?

Thanks for your answer Vincent, yes I updated to the lastest "actions" versions and I replaced all the files.
With the last Vpinmame version (1154) the flashers are fixed on Scared Stiff, but there's still this DOF issue on Gilligan's Island.
It's definitely a Vpinmame issue cause rolling back to a previous version is fixing it.
The strangest thing is that some contactors are working (bumpers, slingshots) but not flippers.

**Comment by rashoultes** [comment]
I am experiencing the same issue with Funhouse

**Comment by Dicentim974** [comment]
Hi, I switched back to 1108 that is the lastest version without any issue.
After this version the Gilligan's Island DOD issue appeared.
Someone also reported me issues with "STTNG cannons acted funny and the game kept losing the ball" with all versions after 1108. Maybe starting your next beta with this 1108 as a basis? Thanks again for your great work !

**Comment by vbousquet** [comment]
@Dicentim974 I've just fixed a bug in this driver I introduced while doing other changes. Could you give it a go and see if things are back to normal ?

**Comment by Dicentim974** [comment]
@vbousquet Hi, I've just tried the [VPinMAME-sc-3.6.0-1167-8b60a2d-win-x64] and unfortunately Gilligan's Island flippers's DOF is still broken. I went back to 1108 and it's ok. Thanks trying to help me.

**Comment by mazjohn** [comment]
Adding that the DOF solenoid flippers in The Machine Bride of Pinbot are also not working (Slings work but flippers do not fire) this was tested with latest vpinmame and vpx x64 releases from today.

**Comment by Dicentim974** [comment]
> Adding that the DOF solenoid flippers in The Machine Bride of Pinbot are also not working (Slings work but flippers do not fire) this was tested with latest vpinmame (1167) and vpx x64 (2031) builds from today.

Hi, thanks for this feedback, I didn't know for BOP.
List of some tables with this DOF flippers issue :
- FunHouse
- Gilligan's Island
- The Machine : Bride of Pinbot
I noticed all of this table have S48 and S46 for flippers DOF setting in configtool?vpuniverse.com
But... Earthshaker have the same S48/S46 and it works great.
We also notified there is no issue with Vpinmame 1108 version.
Fingers crossed hoping our magicians @vbousquet @toxieainc can fix this in a future Vpinmame version. :)

**Comment by mazjohn** [comment]
Another update: Adding that the DOF solenoid flippers in Terminator 2 are also not working (Slings work but flippers do not fire) this was tested with latest vpinmame (1167) and vpx x64 (2035) builds from today.

**Comment by Dicentim974** [comment]
Hi, thanks for your feedback @mazjohn 
Here is the update list of tables with issue (no contactors or selonedoids feedback for flippers) :
- Gilligan's island
- T2
- The Machine Bride of Pinbot
- FunHouse
Thanks @vbousquet @toxieainc

**Comment by Dicentim974** [comment]
Hi, Problem solved, thanks to Overridex on VPU who found the fix :
Simply edit the table script to : 
Const UseVPMModSol = false
or Const UseVPMModSol = 0
On the tables having the issue these lines were on "True" or "1".

**Comment by Dicentim974** [comment]
Hi, Problem solved, thanks to Overridex on VPU who found the fix :
Simply edit the table script to :
Const UseVPMModSol = false
or Const UseVPMModSol = 0
On the tables having the issue these lines were on "True" or "1".

**Comment by toxieainc** [comment]
Unfortunately thats more a workaround than a real fix i think

**Comment by Dicentim974** [comment]
> Unfortunately thats more a workaround than a real fix i think

Sure but as long as a few tables are concerned that's not a big deal for me to edit a few lines. 
You definitely changed something in Vpinmame code since version 1108, but I really don't know how it works 😁.

**Comment by mandermannen** [comment]
i tried to change the Usesolenoids = 2 for Terminator 2 but that disables the flippers

**Comment by bbecausereasonss** [comment]
Yikes.

**Comment by rashoultes** [comment]
I just tried this VPinMame update and I am still not getting my flipper solenoids to fire?  I tested T2, Fuinhouse and Gilligians Island and all of them still have the flipper issue where the solenoids dont fire.

**Comment by Dicentim974** [comment]
> @vbousquet I just tried this VPinMame update and I am still not getting my flipper solenoids to fire? I tested T2, Fuinhouse and Gilligians Island and all of them still have the flipper issue where the solenoids dont fire. Thank you for trying to fix this!

The update works ok for me, did you reinstall Vpinmame using setup.exe and setup64.exe ?

**Comment by rashoultes** [comment]
> > @vbousquet I just tried this VPinMame update and I am still not getting my flipper solenoids to fire? I tested T2, Fuinhouse and Gilligians Island and all of them still have the flipper issue where the solenoids dont fire. Thank you for trying to fix this!
> 
> The update works ok for me, did you reinstall Vpinmame using setup.exe and setup64.exe ?


@Dicentim974 Oh really!  I did re-run the setup.exe and setup64.exe.

**Comment by rashoultes** [comment]
@vbousquet @Dicentim974 correction, after a reboot I now have flippers that are working with DOF.  Thank you for figuring this out!!!

**Comment by mandermannen** [comment]
It works also for me but now Lethal Weapon 3 doesnt have flipper DOF-sounds

**Comment by Dicentim974** [comment]
In fact a lot of tables have now the issue : Breakout, Street fighter 2,Ripley's believe it or not.
But I think @vbousquet and @toxieainc are on the right way to fix that.

**Comment by mandermannen** [comment]
Lets hope so. Also godzilla and last action hero has it

**Comment by mandermannen** [comment]
And the flippers of Apollo 13 arent working anymore

**Comment by bthitney** [comment]
> And the flippers of Apollo 13 arent working anymore

+1 -- 1187 x64 fixed the T2/no DOF issue, but no flippers in Apollo 13.
